# Generated by Django 4.2.4 on 2023-08-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',)},
        ),
    ]
