# Generated by Django 4.2.4 on 2023-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
